name: Rust Build

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Check
        run: cargo check --locked

      - name: Test
        run: cargo test --locked

      - name: Clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

      - name: Build Optimized Binary
        run: |

          export RUSTFLAGS="-C target-cpu=native -C llvm-args=-inline-threshold=500"
          
          cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gptload-rs-release
          path: target/release/gptload-rs 
